import { createContext, useContext, useEffect, useRef, useState } from 'react';

const CraftContext = createContext();

export const TRANSLATIONS = {
  hi: {
    code: "hi-IN",
    name: "हिंदी",
    tagline: "आपका शिल्प • आपकी कहानी • आपका बाज़ार",
    heroText: "कारीगर से व्यापारी तक का डिजिटल सफर",
    desc: "बिना लिखे या फोटो एडिट किए, केवल बोलकर अपनी पेशेवर डिजिटल लिस्टिंग बनाएं।",
    f1: "फोटो स्टूडियो", f1_sub: "स्वच्छ बैकग्राउंड",
    f2: "भाषिणी वॉइस", f2_sub: "बिना टाइपिंग",
    f3: "उचित मूल्य", f3_sub: "लागत अनुसार",
    startBtn: "शुरू करें / Launch Studio",
    listen: "सुनिए (Audio)",
    speaking: "बोल रहा है...",
    speechText: "शिल्पसाथी में आपका स्वागत है। अपने हस्तशिल्प की तस्वीर लें और बोलकर विवरण दर्ज करें।",
    studioTitle: "कलाकार डैशबोर्ड",
    activeListings: "सक्रिय उत्पाद",
    itemsCount: "3 वस्तुएं",
    benchmarkPrice: "बाज़ार औसत दर",
    assistantReady: "स्मार्ट सहायक तैयार है",
    assistantHint: "नया उत्पाद जोड़ना है? एक फोटो खींचें और हिंदी में बोलकर बताएं।",
    addBtn: "नया शिल्प जोड़ें",
    photoTitle: "शिल्प का फोटो लें",
    photoSub: "हमारा AI बैकग्राउंड को स्वतः साफ और प्रकाश ठीक करता है",
    photoBtn: "फोटो खींचें / गैलरी से चुनें",
    supportedCrafts: "मिट्टी, वस्त्र, काष्ठ, धातु एवं सभी हस्तशिल्प",
    studioCleaned: "स्टूडियो क्लीनिंग पूर्ण",
    continueVoice: "आवाज़ से विवरण दर्ज करें",
    voiceTitle: "अपने शिल्प की कहानी बताएं",
    voiceSub: "अपनी भाषा में बोलें। भाषिणी इसे कैटलॉग में बदलेगा।",
    tapSpeak: "बोलने के लिए दबाएं",
    voiceExample: "उदाहरण: यह एक हस्तनिर्मित मिट्टी का फूलदान है, जिसे पारंपरिक चाक पर बनाया गया है...",
    catalogTitle: "स्वतः तैयार कैटलॉग",
    catalogSub: "भाषिणी एवं AI द्वारा निकाला गया विवरण (सुधार सकते हैं)",
    calcPriceBtn: "उचित मूल्य गणना करें",
    priceTitle: "AI मूल्य सहायक",
    priceSub: "कारीगर लागत और समय के अनुसार पारदर्शी मूल्य",
    suggestedRange: "अनुशंसित मूल्य सीमा",
    setFinalPrice: "अपना विक्रय मूल्य तय करें (₹)",
    reviewBtn: "लिस्टिंग की जांच करें",
    verifyTitle: "लिस्टिंग की पुष्टि करें",
    verifySub: "साझा करने से पहले पूरी जानकारी जांचें",
    publishBtn: "डिजिटल लिस्टिंग प्रकाशित करें",
    publishedTitle: "लिस्टिंग तैयार है!",
    publishedSub: "आपका शिल्प अब डिजिटल बाज़ार में बिकने के लिए तैयार है",
    shareWhatsapp: "व्हाट्सएप पर शेयर करें",
    homeBtn: "होम पेज",
    navStudio: "डैशबोर्ड", navCatalog: "कैटलॉग", navAdd: "जोड़ें",navProfile: "भाषा",
beyondTitle: "मेलों से आगे",
beyondDesc: "अपने पारंपरिक शिल्प को साल भर बेचें। सूरजकुंड मेला, दिल्ली हाट और शिल्प समागम जैसे मौसमी मेलों की सीमाओं से आगे बढ़ें।",


  },
  en: {
    code: "en-IN",
    name: "English",
    tagline: "Your Craft • Your Story • Your Market",
    heroText: "From Rural Artisan to Global Market",
    desc: "Create professional e-commerce listings by simply speaking in your mother tongue.",
    f1: "AI Studio", f1_sub: "Auto Light",
    f2: "BHASHINI", f2_sub: "Voice Driven",
    f3: "Fair Price", f3_sub: "Heuristic",
    startBtn: "Launch Studio / शुरू करें",
    listen: "Listen (Audio)",
    speaking: "Speaking...",
    speechText: "Welcome to ShilpSaathi. Photograph your craft and speak out loud to create your market catalog.",
    studioTitle: "Artisan Studio",
    activeListings: "Active Crafts",
    itemsCount: "3 Items",
    benchmarkPrice: "Avg. Market Benchmark",
    assistantReady: "Smart Assistant Ready",
    assistantHint: "Ready to catalog? Take one photo and speak out its story naturally.",
    addBtn: "Add New Craft Item",
    photoTitle: "Photograph Craft",
    photoSub: "Our AI cleans cluttered backgrounds and normalizes lighting",
    photoBtn: "Capture / Select Photo",
    supportedCrafts: "Clay, Textiles, Woodwork, Metal & Handmade Crafts",
    studioCleaned: "Studio Cleaned",
    continueVoice: "Proceed to Voice Details",
    voiceTitle: "Speak Your Craft's Story",
    voiceSub: "Speak naturally. BHASHINI converts your speech into bilingual data.",
    tapSpeak: "Tap to Speak",
    voiceExample: "Example: Handcrafted earthen terracotta floral vase made on traditional potter's wheel...",
    catalogTitle: "AI Auto-Catalog",
    catalogSub: "Extracted from speech via BHASHINI (Tap to edit)",
    calcPriceBtn: "Calculate Fair Price",
    priceTitle: "AI Pricing Assistant",
    priceSub: "Fair pricing calculated from materials and skilled labor hours",
    suggestedRange: "Suggested Market Range",
    setFinalPrice: "Set Your Selling Price (₹)",
    reviewBtn: "Review Listing",
    verifyTitle: "Verify Your Listing",
    verifySub: "Full human control: verify details before sharing",
    publishBtn: "Publish Digital Listing",
    publishedTitle: "Listing Published!",
    publishedSub: "Your craft is now digital and ready to share",
    shareWhatsapp: "Share on WhatsApp",
    homeBtn: "Home",
    navStudio: "Studio", navCatalog: "Catalog", navAdd: "Add",navProfile: "Language",
beyondTitle: "Beyond Physical Exhibitions",
beyondDesc: "Sell your heritage crafts year-round. Overcome the seasonal limits of Surajkund Mela, Dilli Haat, and Shilp Samagam.",

  },
  bn: {
    code: "bn-IN",
    name: "বাংলা",
    tagline: "আপনার শিল্প • আপনার গল্প • আপনার বাজার",
    heroText: "গ্রামীণ কারিগর থেকে ডিজিটাল বাজার",
    desc: "টাইপ বা ফটো এডিটিং ছাড়াই আপনার ভাষায় কথা বলে অনলাইন তালিকা তৈরি করুন।",
    f1: "ফটো স্টুডিও", f1_sub: "স্বচ্ছ ছবি",
    f2: "ভাষিণী ভয়েস", f2_sub: "টাইপিং ছাড়া",
    f3: "ন্যায্য মূল্য", f3_sub: "সঠিক দাম",
    startBtn: "শুরু করুন / Launch Studio",
    listen: "শুনুন (Audio)",
    speaking: "বলছে...",
    speechText: "শিল্পসাথীতে আপনাকে স্বাগতম। আপনার পণ্যের ছবি তুলুন এবং কথা বলে বিবরণ দিন।",
    studioTitle: "কারিগর ড্যাশবোর্ড",
    activeListings: "সক্রিয় পণ্য",
    itemsCount: "৩টি পণ্য",
    benchmarkPrice: "গড় বাজার দর",
    assistantReady: "সহায়ক প্রস্তুত",
    assistantHint: "একটি ছবি তুলুন এবং নিজের ভাষায় কথা বলে বিবরণ দিন।",
    addBtn: "নতুন পণ্য যোগ করুন",
    photoTitle: "পণ্যের ছবি তুলুন",
    photoSub: "আমাদের AI ছবির ব্যাকগ্রাউন্ড পরিষ্কার ও আলো ঠিক করে",
    photoBtn: "ছবি তুলুন / সিলেক্ট করুন",
    supportedCrafts: "মাটি, তাঁত, কাঠ, ধাতু ও সব হস্তশিল্প",
    studioCleaned: "স্টুডিও পরিষ্কার",
    continueVoice: "ভয়েস বিবরণে যান",
    voiceTitle: "পণ্যের গল্প বলুন",
    voiceSub: "নিজের ভাষায় বলুন। ভাষিণী একে ক্যাটালগে রূপান্তর করবে।",
    tapSpeak: "বলতে স্পর্শ করুন",
    voiceExample: "উদাহরণ: এটি একটি হাতে তৈরি মাটির ফুলদানি যা চাকার সাহায্যে তৈরি...",
    catalogTitle: "স্বয়ংক্রিয় ক্যাটালগ",
    catalogSub: "ভাষিণী দ্বারা প্রস্তুতকৃত বিবরণ (সম্পাদনাযোগ্য)",
    calcPriceBtn: "ন্যায্য মূল্য নির্ধারণ করুন",
    priceTitle: "AI মূল্য সহায়ক",
    priceSub: "উপাদান খরচ ও শ্রম অনুযায়ী সঠিক দামের সুপারিশ",
    suggestedRange: "প্রস্তাবিত দামের সীমা",
    setFinalPrice: "আপনার বিক্রয় মূল্য দিন (₹)",
    reviewBtn: "তালিকা যাচাই করুন",
    verifyTitle: "তথ্য যাচাই করুন",
    verifySub: "প্রকাশের পূর্বে সমস্ত তথ্য দেখে নিন",
    publishBtn: "ডিজিটাল তালিকা প্রকাশ করুন",
    publishedTitle: "তালিকা প্রকাশিত!",
    publishedSub: "আপনার শিল্প এখন অনলাইনে বিক্রি করতে প্রস্তুত",
    shareWhatsapp: "হোয়াটসঅ্যাপে শেয়ার করুন",
    homeBtn: "হোম",
    navStudio: "স্টুডিও", navCatalog: "ক্যাটালগ", navAdd: "যোগ", navProfile: "ভাষা",
beyondTitle: "প্রদর্শনীর বাইরেও",
beyondDesc: "সারা বছর আপনার ঐতিহ্যবাহী পণ্য বিক্রি করুন। সুরজকুণ্ড মেলা, দিল্লি হাট এবং শিল্প সমাগমের মৌসুমি সীমা ছাড়িয়ে যান।",

  },
  ta: {
    code: "ta-IN",
    name: "தமிழ்",
    tagline: "உங்கள் கைவினை • உங்கள் கதை • உங்கள் சந்தை",
    heroText: "பாரம்பரிய கைவினைஞர்களுக்கான டிஜிட்டல் தளம்",
    desc: "எழுதாமல் அல்லது திருத்தாமல் உங்கள் குரல் மூலம் தொழில்முறை பட்டியலை உருவாக்கவும்.",
    f1: "AI ஸ்டுடியோ", f1_sub: "ஒளி சீரமைப்பு",
    f2: "பாஷிணி குரல்", f2_sub: "டைப்பிங் இல்லை",
    f3: "நியாயமான விலை", f3_sub: "நேர்மையான லாபம்",
    startBtn: "தொடங்குங்கள் / Launch Studio",
    listen: "கேளுங்கள் (Audio)",
    speaking: "பேசுகிறது...",
    speechText: "சில்ப்சாதிக்கு நல்வரவு. உங்கள் கைவினைப் பொருளைப் படம் பிடித்து குரல் மூலம் பேசுங்கள்.",
    studioTitle: "கைவினைஞர் மையம்",
    activeListings: "செயலில் உள்ளவை",
    itemsCount: "3 பொருட்கள்",
    benchmarkPrice: "சந்தை சராசரி விலை",
    assistantReady: "உதவியாளர் தயார்",
    assistantHint: "புகைப்படம் எடுத்து உங்கள் மொழியில் அதன் விபரங்களைச் சொல்லுங்கள்.",
    addBtn: "புதிய கைவினை சேர்",
    photoTitle: "பொருளைப் படம் பிடிக்கவும்",
    photoSub: "பின்னணியை தானாகவே AI நீக்கி வெளிச்சத்தை சீரமைக்கும்",
    photoBtn: "புகைப்படம் எடுக்கவும்",
    supportedCrafts: "மண்பாண்டம், நெசவு, மர வேலைப்பாடு மற்றும் அனைத்தும்",
    studioCleaned: "தூய்மையாக்கப்பட்டது",
    continueVoice: "குரல் பதிவுக்கு செல்லவும்",
    voiceTitle: "கைவினையின் கதையைச் சொல்லுங்கள்",
    voiceSub: "இயல்பாகப் பேசுங்கள். பாஷிணி அதைத் தகவலாக மாற்றும்.",
    tapSpeak: "பேச தொடவும்",
    voiceExample: "உதாரணம்: இது பாரம்பரிய முறையில் சக்கரத்தில் செய்யப்பட்ட களிமண் பூச்சாடி...",
    catalogTitle: "தானியங்கு பட்டியல்",
    catalogSub: "குரலிலிருந்து உருவாக்கப்பட்ட விவரங்கள் (திருத்தலாம்)",
    calcPriceBtn: "விலையைக் கணக்கிடுங்கள்",
    priceTitle: "AI விலை உதவியாளர்",
    priceSub: "மூலப்பொருள் மற்றும் உழைப்புக்கேற்ற நியாயமான விலை",
    suggestedRange: "பரிந்துரைக்கப்பட்ட விலை வரம்பு",
    setFinalPrice: "விற்பனை விலை நிர்ணயிக்கவும் (₹)",
    reviewBtn: "சரிபார்க்கவும்",
    verifyTitle: "விவரங்களைச் சரிபார்க்கவும்",
    verifySub: "வெளியிடுவதற்கு முன் உறுதிப்படுத்தவும்",
    publishBtn: "பட்டியலை வெளியிடவும்",
    publishedTitle: "வெளியிடப்பட்டது!",
    publishedSub: "உங்கள் கைவினைப்பொருள் சந்தைக்குத் தயார்",
    shareWhatsapp: "வாட்ஸ்அப்பில் பகிரவும்",
    homeBtn: "முகப்பு",
    navStudio: "மையம்", navCatalog: "பட்டியல்", navAdd: "சேர்", navProfile: "மொழி",
beyondTitle: "கண்காட்சிகளுக்கு அப்பால்",
beyondDesc: "உங்கள் பாரம்பரிய கைவினைப் பொருட்களை ஆண்டு முழுவதும் விற்கவும். சூரஜ்குண்ட் மேளா, தில்லி ஹாட் போன்ற பருவகால வரம்புகளைத் தாண்டவும்.",

// te block
  },
  te: {
    code: "te-IN",
    name: "తెలుగు",
    tagline: "మీ కళ • మీ కథ • మీ మార్కెట్",
    heroText: "చేతివృత్తుల కళాకారులకు డిజిటల్ వేదిక",
    desc: "టైప్ చేయకుండా లేదా ఫోటో ఎడిటింగ్ లేకుండా మీ గొంతుతోనే డిజిటల్ కేటలాగ్ రూపొందించండి.",
    f1: "ఫోటో స్టూడియో", f1_sub: "క్లీన్ బ్యాక్‌గ్రౌండ్",
    f2: "భాషిణి వాయిస్", f2_sub: "టైపింగ్ అవసరం లేదు",
    f3: "సరసమైన ధర", f3_sub: "సరైన రేటు",
    startBtn: "ప్రారంభించండి / Launch Studio",
    listen: "వినండి (Audio)",
    speaking: "మాట్లాడుతోంది...",
    speechText: "శిల్పసాథికి స్వాగతం. మీ వస్తువును ఫోటో తీసి మాట్లాడి వివరాలు చెప్పండి.",
    studioTitle: "కళాకారుల స్టూడియో",
    activeListings: "యాక్టివ్ వస్తువులు",
    itemsCount: "3 వస్తువులు",
    benchmarkPrice: "సగటు మార్కెట్ ధర",
    assistantReady: "అసిస్టెంట్ సిద్ధంగా ఉంది",
    assistantHint: "ఫోటో తీసి మీ స్వంత భాషలో వివరాలు మాట్లాడండి.",
    addBtn: "కొత్త వస్తువును జోడించండి",
    photoTitle: "వస్తువును ఫోటో తీయండి",
    photoSub: "మా AI బ్యాక్‌గ్రౌండ్‌ను క్లీన్ చేసి వెలుతురును సరిచేస్తుంది",
    photoBtn: "ఫోటో తీయండి / ఎంచుకోండి",
    supportedCrafts: "మట్టి, చేనేత, చెక్క, లోహ కళారూపాలు",
    studioCleaned: "స్టూడియో క్లీన్డ్",
    continueVoice: "వాయిస్ వివరాలకు వెళ్లండి",
    voiceTitle: "కళ యొక్క కథను చెప్పండి",
    voiceSub: "సహజంగా మాట్లాడండి. భాషిణి దీనిని డేటాగా మారుస్తుంది.",
    tapSpeak: "మాట్లాడటానికి నొక్కండి",
    voiceExample: "ఉదాహరణ: సాంప్రదాయ చక్రంపై తయారు చేయబడిన చేతితో చేసిన మట్టి కుండ...",
    catalogTitle: "ఆటో కేటలాగ్",
    catalogSub: "వాయిస్ ద్వారా సేకరించబడిన వివరాలు (సవరించవచ్చు)",
    calcPriceBtn: "సరసమైన ధరను లెక్కించండి",
    priceTitle: "AI ధర సహాయకుడు",
    priceSub: "ముడిసరుకు ఖర్చు మరియు సమయం ఆధారంగా సరైన ధర",
    suggestedRange: "సిఫార్సు చేయబడిన ధర శ్రేణి",
    setFinalPrice: "అమ్మకపు ధరను నిర్ణయించండి (₹)",
    reviewBtn: "వివరాలు సమీక్షించండి",
    verifyTitle: "వివరాలను నిర్ధారించండి",
    verifySub: "ప్రకటించే ముందు సమాచారాన్ని సరిచూసుకోండి",
    publishBtn: "డిజిటల్ జాబితాను ప్రచురించండి",
    publishedTitle: "ప్రచురించబడింది!",
    publishedSub: "మీ కళ ఇప్పుడు మార్కెట్లో అమ్మకానికి సిద్ధంగా ఉంది",
    shareWhatsapp: "వాట్సాప్‌లో షేర్ చేయండి",
    homeBtn: "హోమ్",
    navStudio: "స్టూడియో", navCatalog: "కేటలాగ్", navAdd: "జోడించు",navProfile: "భాష",
beyondTitle: "ప్రదర్శనలకు మించి",
beyondDesc: "మీ సాంప్రదాయ కళాఖండాలను ఏడాది పొడవునా అమ్మండి. సూరజ్‌కుండ్ మేళా, దిల్లీ హాట్ వంటి కాలానుగుణ పరిమితులను అధిగమించండి.",

  },
  mr: {
    code: "mr-IN",
    name: "मराठी",
    tagline: "तुमची कला • तुमची कथा • तुमची बाजारपेठ",
    heroText: "कारागीर ते डिजिटल उद्योजक",
    desc: "कोणतेही टायपिंग किंवा फोटो संपादन न करता, फक्त बोलून व्यावसायिक कॅटलॉग तयार करा.",
    f1: "फोटो स्टुडिओ", f1_sub: "स्वच्छ पार्श्वभूमी",
    f2: "भाषिणी व्हॉइस", f2_sub: "टायपिंग नाही",
    f3: "योग्य किंमत", f3_sub: "वाजवी दर",
    startBtn: "सुरू करा / Launch Studio",
    listen: "ऐका (Audio)",
    speaking: "बोलत आहे...",
    speechText: "शिल्पसाथीमध्ये आपले स्वागत आहे. आपल्या हस्तकलेचा फोटो घ्या आणि बोलून माहिती नोंदवा.",
    studioTitle: "कारागीर डॅशबोर्ड",
    activeListings: "सक्रिय उत्पादने",
    itemsCount: "३ वस्तू",
    benchmarkPrice: "सरासरी बाजार भाव",
    assistantReady: "स्मार्ट सहाय्यक सज्ज",
    assistantHint: "नवीन वस्तू जोडायची आहे? एक फोटो काढा आणि मराठीत बोलून माहिती सांगा.",
    addBtn: "नवीन हस्तकला जोडा",
    photoTitle: "हस्तकलेचा फोटो घ्या",
    photoSub: "आमचे AI अस्वच्छ पार्श्वभूमी काढून प्रकाश नियंत्रित करते",
    photoBtn: "फोटो काढा / निवडा",
    supportedCrafts: "माती, कापड, लाकूड, धातू आणि सर्व हस्तकला",
    studioCleaned: "स्टुडिओ क्लिनिंग पूर्ण",
    continueVoice: "आवाजाद्वारे माहिती द्या",
    voiceTitle: "हस्तकलेची गोष्ट सांगा",
    voiceSub: "आपल्या भाषेत बोला. भाषिणी याचे कॅटलॉगमध्ये रूपांतर करेल.",
    tapSpeak: "बोलण्यासाठी स्पर्श करा",
    voiceExample: "उदाहरण: हे चाकावर बनवलेले पारंपरिक मातीचे सुंदर फुलदाणी आहे...",
    catalogTitle: "स्वयंनिर्मित कॅटलॉग",
    catalogSub: "भाषिणीद्वारे काढलेली माहिती (बदल करू शकता)",
    calcPriceBtn: "वाजवी किंमत ठरवा",
    priceTitle: "AI किंमत सहाय्यक",
    priceSub: "साहित्याचा खर्च आणि मेहनतीनुसार योग्य दर",
    suggestedRange: "शिफारस केलेली किंमत मर्यादा",
    setFinalPrice: "विक्री किंमत निश्चित करा (₹)",
    reviewBtn: "तपासा",
    verifyTitle: "माहिती तपासा",
    verifySub: "शेअर करण्यापूर्वी सर्व माहितीची खात्री करा",
    publishBtn: "डिजिटल लिस्टिंग प्रकाशित करा",
    publishedTitle: "लिस्टिंग तयार आहे!",
    publishedSub: "आपली कला आता बाजारात विक्रीसाठी सज्ज आहे",
    shareWhatsapp: "व्हॉट्सॲपवर शेअर करा",
    homeBtn: "मुख्य पान",
    navStudio: "डॅशबोर्ड", navCatalog: "कॅटलॉग", navAdd: "जोडा", navProfile: "भाषा",
beyondTitle: "मेळ्यांच्या पलीकडे",
beyondDesc: "आपली पारंपरिक कला वर्षभर विका. सुरजकुंड मेळा, दिल्ली हाट यांसारख्या हंगामी मर्यादा ओलांडा.",
  }
};
export function CraftProvider({ children }) {
  const [currentStep, setCurrentStep] = useState(1);
  const [lang, setLang] = useState('hi');
  const [isLoading, setIsLoading] = useState(false);
  const [loadingMessage, setLoadingMessage] = useState('');
  const [showLangModal, setShowLangModal] = useState(false);
  const [processingStages, setProcessingStages] = useState([]);
  const [currentStage, setCurrentStage] = useState('');
  const originalPreviewUrlRef = useRef(null);

  const [productData, setProductData] = useState({
    originalImage: null,
    enhancedImage: "https://images.unsplash.com/photo-1590736969955-71cc94801759?w=800&auto=format&fit=crop",
    name: "Handcrafted Terracotta Earthen Vase",
    category: "Clay & Ceramic Crafts",
    material: "Traditional Riverbed Clay",
    colour: "Natural Ochre & Terracotta",
    description_hi: "हाथ से चाक पर तैयार की गई शुद्ध मिट्टी की सुराही। प्राकृतिक रूप से पकाई गई और पर्यावरण के अनुकूल।",
    description_en: "Handmade wheel-thrown terracotta vase crafted from local riverbed clay. Eco-friendly with natural earthen finish.",
    keywords: ["pottery", "terracotta", "handmade", "eco-friendly"],
    price_min: 750,
    price_max: 1100,
    final_price: 890,
    price_reasoning: "Material Cost (₹220) + 5 hrs hand-turning + category benchmark markup."
  });

  const t = TRANSLATIONS[lang] || TRANSLATIONS.hi;

  const updateProduct = (fields) => setProductData(prev => ({ ...prev, ...fields }));
  const setOriginalPreview = (file) => {
    if (originalPreviewUrlRef.current) {
      URL.revokeObjectURL(originalPreviewUrlRef.current);
    }
    const url = URL.createObjectURL(file);
    originalPreviewUrlRef.current = url;
    updateProduct({ originalImage: url, enhancedImage: null, original_image_url: null });
    return url;
  };
  const clearOriginalPreview = () => {
    if (originalPreviewUrlRef.current) {
      URL.revokeObjectURL(originalPreviewUrlRef.current);
      originalPreviewUrlRef.current = null;
    }
  };
  useEffect(() => clearOriginalPreview, []);
  const nextStep = () => setCurrentStep(prev => prev + 1);
  const prevStep = () => setCurrentStep(prev => Math.max(1, prev - 1));
  const goToStep = (step) => setCurrentStep(step);

  return (
    <CraftContext.Provider value={{
      currentStep, nextStep, prevStep, goToStep,
      lang, setLang, t,
      productData, updateProduct,
      setOriginalPreview, clearOriginalPreview,
      isLoading, setIsLoading,
      loadingMessage, setLoadingMessage,
      showLangModal, setShowLangModal,
      processingStages, setProcessingStages,
      currentStage, setCurrentStage
    }}>
      {children}
    </CraftContext.Provider>
  );
}

export const useCraft = () => useContext(CraftContext);
